version: "3"
services:
  db: 
    image: postgres:9.6.3-alpine
    environment:
      POSTGRES_USER: "tertius"
      POSTGRES_PASSWORD: "R00T@admin123"
      POSTGRES_DB: "ems"
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    environment:
      MATERIA_MODE: "production"
      NO_HOST: "true"